version: '3.1'

services:
  lm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: lm-minimal:latest
    container_name: lm-minimal
    restart: always
    environment:
      FLASK_ENV: development
    volumes:
      - /home/luca/commentsToCode/cloned/:/labeling-machine/data/
      #- inline-labeling-data:/labeling-machine/webapp/db
      - /home/antonio/inline-labeling/db/:/labeling-machine/webapp/db/
    ports:
      - '45000:5000'
#volumes:
#  inline-labeling-data:
