version: '3.1'

services:
  lm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: lm-comment2code:latest
    container_name: lm-comment2code
    restart: always
    environment:
      FLASK_ENV: development
    volumes:
      - /home/luca/commentsToCode/cloned/:/labeling-machine/data/
      #- inline-labeling-data:/labeling-machine/webapp/db
      - /home/antonio/inline-labeling/db/:/labeling-machine/webapp/db/
    ports:
      - '45001:5000'
#volumes:
#  inline-labeling-data:
