version: '3.1'

services:
  lm:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: lm-minimal:latest
    container_name: lm-minimal
    restart: always
    environment:
      FLASK_ENV: development
    volumes:
      #- labeling-data:/labeling-machine/webapp/db
      - inline-labeling-data:/labeling-machine/webapp/db
    ports:
      - '45000:5000'
volumes:
  inline-labeling-data: